name: Trigger install.sh script on predefined servers
on: push
#  release:
#    types:
#      - published
jobs:
  deploy:
    runs-on: access
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List my path
        run: ./install.sh
      - name: Show Output
        run: 'echo ${{ steps.deploy.outputs.url }}'
